export const CHECK_AUTH_STATUS_SUCCESS = 'CHECK_AUTH_STATUS_SUCCESS'
export const CHECK_AUTH_STATUS_FAILURE = 'CHECK_AUTH_STATUS_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
